name: 


on:
  push:
    branches: [main]


jobs:
  my-first-workflow:
    runs-on: ubuntu-latest



    steps:
    - name: Echo the branch name
      run: echo "Current branch - ${{ github.ref_name }}"
    - name: Checkout the current repo
      uses: actions/checkout@v3
    - name:
      run:
    - name:
      run:
    - name:
      run: