name: My CICD Workshop


on:
  push:
    branches: 
      - 'v[0-9]+.[0-9]+'


jobs:
  Workshop-workflow:
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the current repo
      uses: actions/checkout@v3                

    - name: Node
      uses: actions/setup-node@v3
      with: 
        node-version: 16

    - name: Create Release
      id: CreateRelease
      uses: actions/create-release@v1     
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: WORKSHOP_CI/CD

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Railway Deployment
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_SECRETS }}
    
    - name: Slack Deployment
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:        
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*DipSA55 CI/CD Assignment Submission*"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nNguyen Binh Tran"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Metriculation:*\nA0265057B"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\ne1045732@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{github.repositoryUrl}}$"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Deployment:*\n<https://ci-cd-project-production.up.railway.app/>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "<https://ci-cd-project-production.up.railway.app/| Open Application>"
                  }
                ]
              }
            ]
          }
      
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOKENS }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK 